# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-sitemap

# Site settings
title: Neutrico - creative web studio
email: info@neutrico.eu
description: Neutrico - creative web studio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://neutrico.eu" # the base hostname & protocol for your site
twitter_username: neutrico
github_username:  neutrico
tagline: creative web studio
# Build settings
markdown: kramdown
exclude:
  [
  .*,
  .git/,
  _sass/,
  .sass-cache/,
  bs-config.js,
  node_modules/,
  CNAME,
  LICENSE,
  README.md,
  package.json,
  postcss.json,
  init.sh
  ]
